name: 'release'

on:
    create:
        tags:

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Inject slug/short variables
                uses: rlespinasse/github-slug-action@v2.x

            -   name: Inject JDK
                uses: actions/setup-java@v1
                with:
                    java-version: 8

            -   name: Build with Maven
                run: mvn package

            -   name: Create Artefaktes
                run: mvn install

            -   name: Upload Release Asset
                id: upload-release-asset
                uses: meeDamian/github-release@2.0
                with:
                    token: ${{ secrets.GITHUB_TOKEN }}
                    draft: false
                    gzip: false
                    body: >
                        aktuelles Changelog befindet sich [hier](https://github.com/applejuicenet/gui-java/blob/master/CHANGELOG.md)
                    files: >
                        target/AJCoreGUI.zip
                        target/AJCoreGUI.zip.sha256.txt
                        target/AJCoreGUI.macOS.zip
                        target/AJCoreGUI.macOS.zip.sha256.txt

            -   name: trigger homebrew update
                uses: peter-evans/repository-dispatch@v1
                with:
                    token: ${{ secrets.REPO_DISPATCH_TOKEN }}
                    repository: applejuicenet/homebrew-packages
                    event-type: gui-update

            -   name: trigger snapcraft update
                uses: peter-evans/repository-dispatch@v1
                with:
                    token: ${{ secrets.REPO_DISPATCH_TOKEN }}
                    repository: applejuicenet/gui-java
                    event-type: snapcraft-update
